spring.application.name=backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://db.fgenwurrfomadigrgtla.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Vaivishu2001$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Validation
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
